### ISSUE TITLE
Constant timestamp

### ISSUE THREAD

**Issue by e5k** [WFP-VAM/vam.whittaker#1] opened 2020-03-11 02:26 UTC
Hello Valentin,

Sorry for contacting you here but the email I sent you bounced back. Is it possible to use the code with observations at non-constant intervals - i.e. not assuming the use of 8-days MODIS NDVI data? Thanks a lot!

S

**Comment by valpesendorfer** [comment] 2020-03-11 12:54
Hi,

I'm not sure if I understand correctly what you mean, maybe you can clarify. Do you mean using a arbitrary timestep?

If so, yes sure. The filter might just behave differently. It's designed to use a regular timeseries. Missing observations will be interpolated by the filter.

**Comment by e5k** [comment] 2020-03-12 02:55
Yes that is what I mean. I have time-series of MODIS NDVI data that I exported from Google Earth Engine. Although originally from the M?D13Q1 datasets I already filtered out cloud-covered dates. 

In the attached csv file is my attempt to format the data, which returns the attached error. Each column is a different point, and since not all points have the same cloud coverage there are a lot of empty cells (initially Nan in the original data frame). Should they be filled with an error value?

Also I am confused on how you could specify the time step in case of arbitrary timestep. Could you clarify that?

Thanks a lot for your help. Hit me a sbiasse [at] ntu [dot] sg if emailing is easier.
[modape.zip](https://github.com/WFP-VAM/vam.whittaker/files/4322060/modape.zip)

**Comment by valpesendorfer** [comment] 2020-03-12 09:22
The error message you get seems to be caused by a bug within the modape script, so it's not an issue with your data.

Regarding the nodata, the current implementation of csv smooth treats all values < 0 as nodata (I know, that might not be too convenient). So having NaNs will not work for the filter. Please set all your missing observations to either 0 or below that.

Regarding the arbitrary timestep, this is just determined by your input. 

Assuming you're having an 8 day timeseries, but want to have a filtered 4 day timeseries as output, you just need to fill the appropriate places with nodata which will be interpolated.

E.g.

raw data (x observations, o no-data):

```
data: x  x  0  x  o  x  x  o  o  x  x
time: 8 16 24 32 40 48 56 64 72 80 88
```

will give you

```
data: x  x  x  x  x  x  x  x  x  x  x
time: 8 16 24 32 40 48 56 64 72 80 88
```

so if you want a different time step (e.g. 4 day) you can convert to

```
data: x  o  x  o  o  o  x  o  o  o  x  o  x  o  o  o  o  o  x  o  x
time: 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 
```

which should give you

```
data: x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x  x
time: 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88
```

Just be aware, that depending on the data / nodata ratio, the filter can behave unexpectedly - particularly when using the optimization.

Since this is a modape issue, I'll close the issue here and open one for the bug over there. Feel free to comment there or file a new issue if anything remains unclear. 
I'd prefer to keep this here on GitHub, so that any useful information is also available to others and not hidden in my inbox.

**Closed by valpesendorfer** 2020-03-12 09:22 UTC

**Comment by e5k** [comment] 2020-03-13 04:19
Great, thanks a lot for your clarifications!
